[en]
  title = "cqqqwq 的小站"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

# [zh-cn]
#   title = "cqqqwq 的小站"
#   languageName = "简体中文"
#   weight = 1
#   languagedir = "ltr"
#   contentdir = "content/zh-cn"