[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 2

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 3

[[main]]
  parent = "posts"
  name = "Tags"
  url = "tags"

[[main]]
  parent = "posts"
  name = "Categories"
  url = "categories"

[[main]]
  parent = "posts"
  name = "Series"
  url = "series"

[[main]]
  identifier = "notes"
  name = "Notes"
  url = "notes"
  weight = 4

[[main]]
  identifier = "gallery"
  name = "Gallery"
  url = "gallery"
  weight = 5


[[main]]
  identifier = "showcase"
  name = "Showcase"
  url = "showcase"
  weight = 6


[[main]]
  identifier = "friends"
  name = "Friends"
  url = "friends"
  weight = 8